### ISSUE TITLE
[WAI Guidance and Upcoming Pages]

### ISSUE THREAD

**Issue by yatil** [w3c/wai-mobile-intro#6]
> The "WAI Guidance" and "Upcoming" pages are still not integrated, though each page was re-organized to hopefully improve clarity, because these still seem like somewhat different kinds of content.

What does integration look like? What is the plan to integrate those two pages? I feel that I’m missing a piece of the puzzle here.

> Question: Does the structure and organization of the "WAI Guidance" and "Upcoming" pages work better now?

I think the organization is ok, but the content should be updated – on the WAI Guidelines page it needs to be explained what UAAG is and what the relationship to Mobile is. Just writing ”UAAG does apply” is not sufficient.

(I think the ”Issues to bear in mind” sections on the WAI guidelines pages would be great intro pages on their own – maybe for a future release.)

I am still not a fan of the “Upcoming” page: It is extremely timely content and some of the things that are under consideration might NOT be upcoming but get dismissed or addressed in a later version of WCAG. I think this page is bad for our overall messaging and has little to no actual information for developers on how to implement accessibility now. I strongly suggest summarizing the principles, but not link to current discussions. We can frame this as best practices and add a paragraph about that some of those practices are being integrated into WCAG as we speak. The page is a bit too list-heavy.

**Comment by bakkenb** [comment]
Quoting Eric...
> I am still not a fan of the “Upcoming” page: It is extremely timely content and some of the things that are under consideration might NOT be upcoming but get dismissed or addressed in a later version of WCAG. I think this page is bad for our overall messaging and has little to no actual information for developers on how to implement accessibility now. I strongly suggest summarizing the principles, but not link to current discussions.

I too still see this as problematic. We typically don't link to ongoing discussions, especially if they are ones that may not make it into the next version of WCAG. This will pose a much more significant amount of work to watch and maintain this resource throughout the year(s) to come.

**Comment by bakkenb** [comment]
I noticed the same thing on the UAAG statement. 
> The UAAG 2.0 guidelines apply to mobile.

If we are going to state that, then add a paragraph of why. It is not sufficient to just give a developer that link and let them try to figure out what it is and how it applies. Some of these developers barely know what WCAG is, let alone even heard of UAAG. A little more information can help make a quick connection that will let them know what is relevant.
