### ISSUE TITLE
[Mini User Scenarios]

### ISSUE THREAD

**Issue by yatil** [w3c/wai-mobile-intro#7]
I like the user scenarios; I think they deserve their own page. I’m not a diversity expert, but I believe we could have more variation in names and origin. (“It’s the World Wide Web, not the Western White Web” as @brucel would say ;-D)

I think the possible solutions should be sentences that explain what the solution is instead of (to be honest) relatively cryptic handles with external links, for example on [Joe’s persona](https://w3c.github.io/wai-mobile-intro/mobile/#joe):

> **Potential solutions:**
> * Touch target size and spacing
> * Touchscreen gestures
> * Placing Buttons where they are easy to access

Could be replaced by:

> **Potential solutions:** Ensure touch target size and spacing is [large enough] and by providing simple [touchscreen gestures]. Buttons should be easily reachable.

(Two notes: 

* The size of the touchscreen target of 9x9 mm is impossible for web developers to implement due to different resolutions – I don’t know what future WCAG 2.1 will say about this, but it might be better to give a CSS pixel size here. 
* I personally try not to use the word “access” in a context other than “accessibility“ to avoid confusion, for example, I would not use ”The user can’t access a site” if it is a network problem. I would say: “The user is unable to reach/get to the site.”
)

**Comment by shawna-slh** [comment]
+1 to "not to use the word “access” in a context other than “accessibility“ to avoid confusion"

**Comment by sharronrush** [comment]
I like the scenarios too, support greater diversity in names and presentation, and think they should not have their own page but be folded in among the content that addresses the issues related to the accessibility barrier they face.
